version: '3.7'
services:
    # Run the node application
    node-app:
        container_name: node-app
        restart: unless-stopped
        build:
            context: ./
        env_file: .env

    # Run the caddy server        
    caddy:
        build:
            context: ./
            dockerfile: Dockerfile.caddy
        container_name: caddy-service
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "2019:2019"
        volumes:            
        - $PWD/Caddyfile-docker:/etc/caddy/Caddyfile
        - $PWD/site:/srv
        - caddy_data:/data
        - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: 